### ISSUE TITLE
[FEATURE] Create the todolist-service initial domain model.

### ISSUE THREAD

**Issue by MarcoFierimonte** [mmonkeyteam/a-new-todos#11]
# Description

As a developer I want to define the domain model of the todolist microservice. 

## Things to do 

- [x] Define tables
- [x] Define columns
- [x] Define fields
- [ ] Create Documentation
- [x] Create SQL scripts

## Notes

I choose to use the Sakila’s convention to define the db domain model.

## References

- [the-power-of-a-good-sql-naming-convention](https://www.xaprb.com/blog/2008/10/26/the-power-of-a-good-sql-naming-convention/)
- [sakila](https://dev.mysql.com/doc/sakila/en/sakila-introduction.html)
- [20-database-design-best](https://dzone.com/articles/20-database-design-best)

**Comment by MarcoFierimonte** [comment]
First todolist domain model version completed.
![todolist.jpg](https://images.zenhubusercontent.com/5d5a5d652e6d2400014d8de5/3c694dd0-1c94-4bea-a5e9-5def4e3925b7)

**Comment by danieleascione** [comment]
Hello @MarcoFierimonte, great work with the picture. I have been missing this :p

I was thinking that in the schema above we're missing a reference to the User. I guess there should be an foreign key in the todolist. 
Another remark: following DDD nomenclature, the root of the aggregate is the entity `todolist` or `activity`?

Once an user is deleted, we should send an event that deletes the entire todolist. 
If this microservice needs info about the user, then, in a first moment it can call the UserService synchronously. In a second moment we'll think about asynchronous mechanisms through a message broker.

**Comment by MarcoFierimonte** [comment]
Hi @audhumla  :) 
[I was thinking that in the schema above we're missing a reference to the User. I guess there should be an foreign key in the todolist.]
Good point, I forgot to add the userId.

[Another remark: following DDD nomenclature, the root of the aggregate is the entity todolist or activity?]
The entity todolist.

[Once an user is deleted, we should send an event that deletes the entire tolist.
If this microservice needs info about the user, then, in a first moment it can call the UserService synchronously. In a second moment we'll think about asynchronous mechanisms through a message broker.]
Yes we need to study the entire process ;)
